import type { FileOverview, H5TreeNode } from './types'

export type ExportTreeNode = {
  path: string
  name: string
  kind: string
  shape?: number[] | null
  dtype?: string
  nbytes?: number
  compression?: string | null
  nwbType?: string
  attrs?: { name: string; dtype: string; shape: number[] | null; preview: string }[]
  children?: ExportTreeNode[]
}

function toExportNode(node: H5TreeNode): ExportTreeNode {
  return {
    path: node.path,
    name: node.name,
    kind: node.kind,
    shape: node.shape,
    dtype: node.dtype,
    nbytes: node.nbytes,
    compression: node.compression,
    nwbType: node.nwbType,
    attrs: node.attrs,
    children: node.children?.map(toExportNode),
  }
}

export function buildTreeExportPayload(overview: FileOverview) {
  return {
    format: 'neuroinspector-tree/v1',
    sourceFile: overview.name,
    fileSizeBytes: overview.sizeBytes,
    formatLabel: overview.formatLabel,
    nwbVersion: overview.nwbVersion,
    groupCount: overview.groupCount,
    datasetCount: overview.datasetCount,
    exportedAt: new Date().toISOString(),
    tree: toExportNode(overview.tree),
  }
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function saveTreeJson(overview: FileOverview) {
  const payload = buildTreeExportPayload(overview)
  const base = overview.name.replace(/\.(nwb|h5|hdf5)$/i, '')
  downloadBlob(
    `${base}.neurotree.json`,
    new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }),
  )
}

function renderHtmlDetails(node: ExportTreeNode): string {
  const metaParts = [
    node.kind,
    node.dtype,
    node.shape?.length ? `(${node.shape.join(' × ')})` : null,
    node.nbytes != null ? `${node.nbytes} B` : null,
  ].filter(Boolean)
  const label = `${escapeHtml(node.name === '/' ? 'root' : node.name)} <span class="meta">${escapeHtml(metaParts.join(' · '))}</span>`

  if (!node.children?.length) {
    return `<div class="leaf" title="${escapeHtml(node.path)}">${label}</div>`
  }
  return `<details open>
    <summary title="${escapeHtml(node.path)}">${label}</summary>
    <div class="kids">${node.children.map(renderHtmlDetails).join('')}</div>
  </details>`
}

function escapeHtml(s: string) {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

/** Interactive HTML tree — open in any browser, expand/collapse with details/summary. */
export function saveTreeHtml(overview: FileOverview) {
  const payload = buildTreeExportPayload(overview)
  const base = overview.name.replace(/\.(nwb|h5|hdf5)$/i, '')
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(overview.name)} — NeuroInspector tree</title>
  <style>
    :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
    body { margin: 1.5rem; line-height: 1.45; }
    h1 { font-size: 1.15rem; margin: 0 0 0.35rem; }
    .sub { color: #667; font-size: 0.9rem; margin-bottom: 1rem; }
    details { margin: 0.15rem 0; }
    summary { cursor: pointer; padding: 0.2rem 0.3rem; border-radius: 6px; }
    summary:hover { background: color-mix(in srgb, CanvasText 8%, Canvas); }
    .kids { margin-left: 1rem; border-left: 1px solid color-mix(in srgb, CanvasText 18%, Canvas); padding-left: 0.55rem; }
    .leaf { padding: 0.15rem 0.3rem; font-family: ui-monospace, monospace; font-size: 0.9rem; }
    .meta { color: #789; font-size: 0.8rem; margin-left: 0.35rem; font-weight: 400; }
    summary { font-family: ui-monospace, monospace; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(overview.name)}</h1>
  <div class="sub">${escapeHtml(overview.formatLabel)} · ${payload.groupCount} groups · ${payload.datasetCount} datasets · exported ${escapeHtml(payload.exportedAt)}</div>
  <p class="sub">Expandable file tree (faithful HDF5/NWB hierarchy). Generated by NeuroInspector.</p>
  ${renderHtmlDetails(payload.tree)}
  <script type="application/json" id="neurotree-json">${JSON.stringify(payload).replaceAll('<', '\\u003c')}</script>
</body>
</html>`
  downloadBlob(`${base}.neurotree.html`, new Blob([html], { type: 'text/html' }))
}
